"""v1

Revision ID: 39c75ac2150f
Revises: 801b86be184b
Create Date: 2025-12-28 07:54:39.934672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '39c75ac2150f'
down_revision: Union[str, None] = '801b86be184b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('language', sa.Enum('unknown', 'en', 'zh', 'hi', 'es', 'fr', 'ar', 'pt', name='language'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('external_url', sa.String(length=2048), nullable=False),
    sa.Column('category', sa.Enum('unknown', 'tutorial', 'deep_dive', 'career', 'project', 'opinion', name='blogcategory'), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('read_time_minutes', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blogs'))
    )
    op.create_table('certifications',
    sa.Column('language', sa.Enum('unknown', 'en', 'zh', 'hi', 'es', 'fr', 'ar', 'pt', name='language'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('issuer_url', sa.String(length=2048), nullable=True),
    sa.Column('issuer_logo_url', sa.String(length=2048), nullable=True),
    sa.Column('credential_id', sa.String(length=100), nullable=True),
    sa.Column('verification_url', sa.String(length=2048), nullable=True),
    sa.Column('date_obtained', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('badge_image_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.Enum('unknown', 'security', 'cloud', 'programming', 'networking', 'database', 'devops', name='certificationcategory'), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_table('experiences',
    sa.Column('language', sa.Enum('unknown', 'en', 'zh', 'hi', 'es', 'fr', 'ar', 'pt', name='language'), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('company_url', sa.String(length=2048), nullable=True),
    sa.Column('company_logo_url', sa.String(length=2048), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.Enum('unknown', 'full_time', 'part_time', 'contract', 'freelance', 'internship', name='employmenttype'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('achievements', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences'))
    )
    op.create_table('projects',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('language', sa.Enum('unknown', 'en', 'zh', 'hi', 'es', 'fr', 'ar', 'pt', name='language'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('github_url', sa.String(length=2048), nullable=True),
    sa.Column('demo_url', sa.String(length=2048), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('docs_url', sa.String(length=2048), nullable=True),
    sa.Column('blog_url', sa.String(length=2048), nullable=True),
    sa.Column('pypi_url', sa.String(length=2048), nullable=True),
    sa.Column('npm_url', sa.String(length=2048), nullable=True),
    sa.Column('ios_url', sa.String(length=2048), nullable=True),
    sa.Column('android_url', sa.String(length=2048), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('code_language', sa.String(length=50), nullable=True),
    sa.Column('code_filename', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('banner_url', sa.String(length=2048), nullable=True),
    sa.Column('screenshots', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=True),
    sa.Column('forks_count', sa.Integer(), nullable=True),
    sa.Column('downloads_count', sa.Integer(), nullable=True),
    sa.Column('users_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'active', 'maintained', 'archived', 'deprecated', name='projectstatus'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('slug', 'language', name='uq_projects_slug_language')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('experiences')
    op.drop_table('certifications')
    op.drop_table('blogs')
    # ### end Alembic commands ###
