"""initial

Revision ID: dd8dcd51358d
Revises: 
Create Date: 2025-12-31 11:56:57.686372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd8dcd51358d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
