"""
ⒸAngelaMos | 2025
constants.py
"""

EMAIL_MAX_LENGTH = 320
PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_HASH_MAX_LENGTH = 1024
FULL_NAME_MAX_LENGTH = 255

TOKEN_HASH_LENGTH = 64
DEVICE_ID_MAX_LENGTH = 255
DEVICE_NAME_MAX_LENGTH = 100
IP_ADDRESS_MAX_LENGTH = 45

API_VERSION = "v1"
API_PREFIX = f"/{API_VERSION}"

LANGUAGE_CODE_MAX_LENGTH = 10

PROJECT_SLUG_MAX_LENGTH = 100
PROJECT_TITLE_MAX_LENGTH = 200
PROJECT_SUBTITLE_MAX_LENGTH = 300
PROJECT_DESCRIPTION_MAX_LENGTH = 2000
PROJECT_CODE_FILENAME_MAX_LENGTH = 512
PROJECT_CODE_LANGUAGE_MAX_LENGTH = 50
PROJECT_STATUS_MAX_LENGTH = 50

EXPERIENCE_COMPANY_MAX_LENGTH = 200
EXPERIENCE_ROLE_MAX_LENGTH = 200
EXPERIENCE_DEPARTMENT_MAX_LENGTH = 100
EXPERIENCE_LOCATION_MAX_LENGTH = 200
EXPERIENCE_EMPLOYMENT_TYPE_MAX_LENGTH = 50

CERTIFICATION_NAME_MAX_LENGTH = 200
CERTIFICATION_ISSUER_MAX_LENGTH = 200
CERTIFICATION_CREDENTIAL_ID_MAX_LENGTH = 100
CERTIFICATION_CATEGORY_MAX_LENGTH = 50

BLOG_TITLE_MAX_LENGTH = 300
BLOG_DESCRIPTION_MAX_LENGTH = 1000
BLOG_CATEGORY_MAX_LENGTH = 50

URL_MAX_LENGTH = 2048
TAG_MAX_LENGTH = 50

DEFAULT_DISPLAY_ORDER = 0

PAGINATION_DEFAULT_SKIP = 0
PAGINATION_DEFAULT_LIMIT = 100
PAGINATION_FEATURED_LIMIT = 10
PAGINATION_MAX_LIMIT = 100
PAGINATION_FEATURED_MAX_LIMIT = 20

CACHE_PREFIX = "portfolio"
CACHE_VERSION = "v1"

CACHE_NS_PROJECTS = "projects"
CACHE_NS_EXPERIENCES = "experiences"
CACHE_NS_CERTIFICATIONS = "certifications"
CACHE_NS_BLOGS = "blogs"
CACHE_NS_GITHUB = "github"

CACHE_TTL_PROJECTS = 86400
CACHE_TTL_EXPERIENCES = 86400
CACHE_TTL_CERTIFICATIONS = 86400
CACHE_TTL_BLOGS = 21600
CACHE_TTL_GITHUB = 3600
